openapi: 3.0.3
info:
  description: Implementation for Carbon Credit Plugin logic
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Hyperledger Cactus Plugin - Carbon Credit
  version: 1.0.0
servers:
- url: /
paths:
  /api/v1/@hyperledger/cactus-plugin-carbon-credit/buy:
    post:
      description: Acquires carbon inventory from a marketplace.
      operationId: buyRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuyResponse'
          description: Successful response
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/@hyperledger/cactus-plugin-carbon-credit/buy
  /api/v1/@hyperledger/cactus-plugin-carbon-credit/retire:
    post:
      description: Abstract burn operation that finalizes an offset on the underlying
        registry for a specific beneficiary and message.
      operationId: retireRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetireRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetireResponse'
          description: Successful response
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/@hyperledger/cactus-plugin-carbon-credit/retire
  /api/v1/@hyperledger/cactus-plugin-carbon-credit/get-available-vcus:
    get:
      description: Get a list of available VCUs (Verified Carbon Units).
      operationId: getAvailableVCUsRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAvailableVCUsRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAvailableVCUsResponse'
          description: Successful response with a list of available VCUs.
      x-hyperledger-cacti:
        http:
          verbLowerCase: get
          path: /api/v1/@hyperledger/cactus-plugin-carbon-credit/get-available-vcus
  /api/v1/@hyperledger/cactus-plugin-carbon-credit/get-vcu-metadata:
    post:
      description: Get metadata for a specific VCU.
      operationId: getVCUMetadataRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetVCUMetadataRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VCUMetadata'
          description: Successful response with VCU metadata.
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/@hyperledger/cactus-plugin-carbon-credit/get-vcu-metadata
components:
  schemas:
    Platform:
      enum:
      - Toucan
      type: string
    Network:
      enum:
      - polygon
      - ethereum
      - celo
      - alfajores
      - base
      - base-sepolia
      type: string
    BuyRequest:
      example:
        paymentToken: paymentToken
        amount: 0.8008281904610115
        walletObject: walletObject
        platform: null
        network: null
      properties:
        platform:
          $ref: '#/components/schemas/Platform'
        network:
          $ref: '#/components/schemas/Network'
        paymentToken:
          type: string
        amount:
          type: number
        walletObject:
          type: string
      required:
      - amount
      - network
      - paymentToken
      - platform
      - walletObject
      type: object
    BuyResponse:
      example:
        assetAmount: assetAmount
        txHashSwap: txHashSwap
        tco2List:
        - amount: amount
          address: address
        - amount: amount
          address: address
      properties:
        txHashSwap:
          type: string
        assetAmount:
          type: string
        tco2List:
          items:
            $ref: '#/components/schemas/BuyResponse_tco2List_inner'
          type: array
      required:
      - assetAmount
      - txHashSwap
      type: object
    RetireRequest:
      example:
        retirementReason: retirementReason
        amounts:
        - 0.8008281904610115
        - 0.8008281904610115
        beneficiary: beneficiary
        objectsList:
        - objectsList
        - objectsList
        message: message
        walletObject: walletObject
        platform: null
        network: null
      properties:
        platform:
          $ref: '#/components/schemas/Platform'
        network:
          $ref: '#/components/schemas/Network'
        walletObject:
          type: string
        objectsList:
          items:
            type: string
          type: array
        amounts:
          items:
            type: number
          type: array
        beneficiary:
          type: string
        message:
          type: string
        retirementReason:
          type: string
      required:
      - amounts
      - beneficiary
      - message
      - network
      - objectsList
      - platform
      - retirementReason
      - walletObject
      type: object
    RetireResponse:
      example:
        txHashRetire: txHashRetire
        retirementCertificate: retirementCertificate
      properties:
        txHashRetire:
          type: string
        retirementCertificate:
          type: string
      required:
      - retirementCertificate
      - txHashRetire
      type: object
    VCUMetadata:
      example:
        symbol: symbol
        totalSupply: 0.8008281904610115
        name: name
        attributes:
        - attributes
        - attributes
      properties:
        name:
          type: string
        symbol:
          type: string
        totalSupply:
          type: number
        attributes:
          items:
            type: string
          type: array
      required:
      - attributes
      - name
      - symbol
      - totalSupply
      type: object
    GetAvailableVCUsRequest:
      example:
        filterCriteria: filterCriteria
        limit: limit
        orderBy: orderBy
        platform: null
        network: null
      properties:
        platform:
          $ref: '#/components/schemas/Platform'
        network:
          $ref: '#/components/schemas/Network'
        filterCriteria:
          type: string
        orderBy:
          type: string
        limit:
          type: string
      required:
      - network
      - platform
      type: object
    GetAvailableVCUsResponse:
      example:
        objectsList:
        - objectsList
        - objectsList
        totalCount: 0.8008281904610115
      properties:
        objectsList:
          items:
            type: string
          type: array
        totalCount:
          type: number
      required:
      - objectsList
      - totalCount
      type: object
    GetVCUMetadataRequest:
      example:
        vcuIdentifier: vcuIdentifier
        projectIdentifier: projectIdentifier
        platform: null
        network: null
      properties:
        platform:
          $ref: '#/components/schemas/Platform'
        network:
          $ref: '#/components/schemas/Network'
        projectIdentifier:
          type: string
        vcuIdentifier:
          type: string
      required:
      - network
      - platform
      - projectIdentifier
      - vcuIdentifier
      type: object
    BuyResponse_tco2List_inner:
      example:
        amount: amount
        address: address
      properties:
        address:
          type: string
        amount:
          type: string
      required:
      - address
      - amount
      type: object
