[profile.default]
solc-version = "0.8.29"
evm-version = "paris"
libs = ["node_modules", "lib"]
src = "src/main/solidity/cross-chain-mechanisms"
out = "src/main/solidity/generated"
test = "src/test/solidity/cross-chain-mechanisms"

# sender = # the address of `msg.sender` in tests
# tx_origin =       # the address of `tx.origin` in tests
block_number = 0                                              # the block number we are at in tests
chain_id = 99                                                 # the chain id we are on in tests
gas_limit = 9223372036854775807                               # the gas limit in tests
gas_price = 0                                                 # the gas price (in wei) in tests
block_base_fee_per_gas = 0                                    # the base fee (in wei) in tests
block_coinbase = '0x0000000000000000000000000000000000000000' # the address of `block.coinbase` in tests
block_timestamp = 0                                           # the value of `block.timestamp` in tests
block_difficulty = 0      
fuzz = { runs = 256 }                                         # the number of fuzz runs for tests
gas_reports = ["*"]

# Fuzzing CI
[profile.ci]
fuzz_runs = 100_00
verbosity = 4

[rpc_endpoints]
# goerli = "${RPC_URL_GOERLI}"
# mainnet = "${RPC_URL_MAINNET}"

[etherscan]
# goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
# mainnet = {key = "${ETHERSCAN_KEY}"}
